<h1><?php $this->out($this->title); ?></h1>

<div>
    <?php echo $this->_viewHelperBroker->getHelper('ClientsMenuHelper')->show(); ?>
</div>

<div>
    <table class="tablesorter-blue">
        <thead>    
            <tr>
                <th>Matricula</th>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?php $this->out($this->ot->getMatricula()); ?></td>
                <td><?php $this->out($this->ot->getFechaHora()->format('d/m/Y')); ?></td>
            </tr>
        </tbody>
    </table>
    <?php if ($this->ot->getIncidencias()): ?>
        <table id="listIncidences" class="table tablesorter-blue">
            <thead>
                <tr>
                    <th>ID</th><th>Autor</th><th>Incidencia</th><th>Matrícula</th><th>Fecha</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->ot->getIncidencias() as $incidencia): ?>
                    <?php if (substr($incidencia['id_cliente'], 0, 1) == 'o'): ?>
                        <tr>
                        <?php else: ?>
                        <tr class="active">
                        <?php endif; ?>
                        <td><?php $this->out($incidencia['id']); ?></td>
                        
                            <td><?php $this->out($this->cliente->getName()) ?></td>
                       <td><?php $this->out($incidencia['matricula']); ?></td>
                        <td><?php $this->out($incidencia['mensaje']); ?></td>
                        <td><?php $this->out($incidencia['fecha']); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div id="pager" class="pager">
            <form>
                <img src="/js/tablesorter/addons/pager/icons/first.png" class="first"/>
                <img src="/js/tablesorter/addons/pager/icons/prev.png" class="prev"/>
                <input type="text" class="pagedisplay"/>
                <img src="/js/tablesorter/addons/pager/icons/next.png" class="next"/>
                <img src="/js/tablesorter/addons/pager/icons/last.png" class="last"/>
                <select class="pagesize">
                    <option selected="selected"  value="10">10</option>
                    <option value="20">20</option>
                    <option value="30">30</option>
                    <option  value="40">40</option>
                </select>
            </form>
        </div>
    <?php else: ?>
        <div class="alert alert-info"><span class="glyphicon glyphicon-info-sign"></span> No constan incidencias para la orden de transporte actual</div>
    <?php endif ?>
    <?php if (isset($this->fotos) && sizeof($this->fotos) > 0): ?>
        <div id="nivo-lightbox-gallery">
            <?php foreach ($this->fotos as $foto): ?>
                <a href="<?php echo $foto->getPath() ?>" title="This is an image title" 
                   data-lightbox-gallery="gallery1">
                    <img class="img-responsive img-thumbnail" width="150px"
                         src="<?php echo $foto->getPath() ?>" 
                         alt="" />
                </a>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <div class="alert alert-warning"><span class="glyphicon glyphicon-warning-sign"></span> No constan fotografías para la orden de transporte actual</div>
    <?php endif; ?>
</div>
<div>
    <?php $this->partial('importjQuery')->render(); ?>
    <?php $this->partial('importTableSorterListIncidences')->render(); ?>
    <?php $this->partial('importCarouselNivo')->render(); ?>
</div>