<h1><?php $this->out($this->title); ?></h1>

<div>
    <?php echo $this->_viewHelperBroker->getHelper('ClientsMenuHelper')->show(); ?>
</div>

<div>
    <table id="listOts" class="table tablesorter-blue">
        <thead>
            <tr>
                <th>Matricula</th>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?php $this->out($this->ot->getMatricula()); ?></td>
                <td><?php $this->out($this->ot->getFechaHora()->format('d/m/Y')); ?></td>
            </tr>
        </tbody>
    </table>
    <form class="row" id="incidence" name="incidence" method="post" action="/clients/reportIncidenceDo/" enctype="multipart/form-data">
        <fieldset class="row">
            <legend>Incidencia</legend>
            <p>Los campos con asterisco son obligatorios</p>
            <input class="row" type="hidden" id="plate" name="plate" value="<?php echo $this->ot->getMatricula() ?>">
            <input class="row" type="hidden" id="date" name="date" value="<?php echo $this->ot->getFechaHora()->format('d/m/Y') ?>">

            <div class="row col-md-6 form-group">
                <label for="message">Texto*</label>
                <textarea id="message" name="message" 
                          placeholder="Escriba aquí su incidencia..." 
                          class="form-control" rows="10"></textarea>
            </div>
            <div class="form-group col-md-6">
                <label for="pictures">Fotografías</label>
                <input id="pictures" class="form-control" name="pictures[]" 
                       type="file" multiple="multiple"/>
                <p class="help-block">*Solo ficheros JPEG</p>
                <div id="logs">
                    <output id="filesInfo" class="col-md-6"></output>
                    <output id="textInfo" class="col-md-6"></output>
                </div>
            </div>
            <div class="row col-lg-12"></div>
            <div class="row col-lg-12"></div>
            <div class="form-group col-md-2">
                <input type="submit" id="submit"
                       class="btn btn-primary form-control" value="Enviar">
            </div>
        </fieldset>
    </form>
</div>
<div>
    <?php $this->partial('importUpload')->render(); ?>
    <?php $this->partial('importTableSorterListOts')->render(); ?>
</div>