<h1><?php echo $this->title ?></h1>

<div>
    <?php echo $this->_viewHelperBroker->getHelper(
        'FormHelper',
        array('action'      => '/login/adminLoginDo/',
              'id'          => 'fr1',
              'method'      => 'post',
              'buttonValue' => 'login',
              'controls'    => array(
                  array(
                      'field'   => 'nombre',
                      'type'    => 'text',
                  ),
                  array(
                      'field'   => 'password',
                      'type'    => 'password',
                  )
              )
        ))->show(); ?>
</div>
