<h1><?php $this->out($this->title); ?></h1>

<div>
    <?php echo $this->_viewHelperBroker->getHelper('AdminMenuHelper')->show(); ?>
</div>

<div>
    <table class="table table-hover">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Email</th>
            <th>Password</th>
        </tr>
    <?php foreach ($this->clients as $client): ?>
        <tr>
            <td><?php $this->out($client->getId()); ?></td>
            <td><?php $this->out($client->getName()); ?></td>
            <td><?php $this->out($client->getEmail()); ?></td>
            <td><?php $this->out($client->getPassword()); ?></td>
            
        </tr>
    <?php endforeach; ?>
    </table>
</div>