<h1><?php $this->out($this->title); ?></h1>

<div>
    <?php echo $this->_viewHelperBroker->getHelper('UsersMenuHelper')->show(); ?>
</div>

<div>
    <?php echo $this->_viewHelperBroker->getHelper(
        'FormHelper',
        array('action'      => '/admin/updateDo/',
              'id'          => 'fr1',
              'method'      => 'post',
              'buttonValue' => 'Actualizar',
              'controls'    => array(
                  array(
                      'field'       => 'id',
                      'type'        => 'number',
                      'value'       => $this->user->getId(),
                      'disabled'    => 'disabled'
                  ),
                  array(
                      'field'       => 'nombre',
                      'type'        => 'text',
                      'value'       => $this->user->getName()
                  ),
                  array(
                      'field'       => 'email',
                      'type'        => 'email',
                      'value'       => $this->user->getEmail()
                  ),
                  array(
                      'field'       => 'password',
                      'type'        => 'text',
                      'value'       => $this->user->getPassword()
                  )
              )
        ))->show(); ?>
</div>